server:
  port: 8082

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommerce_customer}
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      

app:
  cors:
    allowed-origins: http://localhost:4200

  jwt:
    secret: ${JWT_SECRET:ZWNvbW1lcmNlLW1pY3Jvc2VydmljZXMtamF2YS0yMS1zcHJpbmctYm9vdC0zLWp3dC1zaGFyZWQtc2VjcmV0LWtleS0yMDI2}
    access-token-minutes: 30
    refresh-token-days: 7

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /v3/api-docs
